import React,{useEffect,useMemo,useState} from 'react';
import {Bell,Search,LogOut,Clock3,CheckCircle2,XCircle,Files,RefreshCw,Filter,Eye,ShieldCheck,ChevronDown,SkipForward} from 'lucide-react';
import {api} from '../api';
import StatCard from '../components/StatCard';
import RequestDrawer from '../components/RequestDrawer';
import {SignedPdfButtons} from '../components/SignedPdfs';
const CHANGE_COLS=[{type:'mobile',label:'Number'},{type:'email',label:'Mail'},{type:'address',label:'Address'},{type:'income',label:'Income'},{type:'bank',label:'Bank'},{type:'nominee',label:'Nominee'}];
const TYPE_LABELS={mobile:'Mobile',email:'Mail',address:'Address',income:'Income',bank:'Bank',nominee:'Nominee',ddpi:'DDPI'};
const humanize=k=>String(k).replace(/_/g,' ').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\b\w/g,m=>m.toUpperCase());
const parseJson=v=>{if(typeof v!=='string')return v;const s=v.trim();if(!/^[[{]/.test(s))return v;try{return JSON.parse(s)}catch{return v}};
function Value({v}){v=parseJson(v);if(v==null||v==='')return '—';if(Array.isArray(v))return v.length?<div className="val-list">{v.map((x,i)=><div key={i} className="val-item">{v.length>1&&<small>#{i+1}</small>}<Value v={x}/></div>)}</div>:'—';if(typeof v==='object'){const e=Object.entries(v);return e.length?<dl className="val-obj">{e.map(([k,x])=><div key={k}><dt>{humanize(k)}</dt><dd><Value v={x}/></dd></div>)}</dl>:'—'}if(typeof v==='boolean')return v?'Yes':'No';return String(v)}
function Cell({r,type,field}){const c=r.changes?.[type];let body='NA';if(c?.on)body=type==='bank'?<><div>Account No: {c[field]||'—'}</div><div>IFSC Code: {c[`${field}_ifsc`]||'—'}</div></>:<Value v={c[field]}/>;return <td className="value-cell"><div className="val-wrap">{body}</div></td>}
function PaymentCell({p,onSkip,busy}){const body=!p?<button className="view-btn skip-btn" disabled={busy} onClick={onSkip}><SkipForward size={16}/> {busy?'Skipping...':'Skip Payment'}</button>:p.skipped?<span className="type-pill skipped">Skipped – moved to next step</span>:<Value v={p}/>;return <td className="value-cell"><div className="val-wrap">{body}</div></td>}
const TYPES=['all','personal','mobile','email','address','income','bank','nominee','ddpi','document'];
export default function DashboardPage(){const [stats,setStats]=useState({});const [rows,setRows]=useState([]);const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [type,setType]=useState('all');const [selected,setSelected]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [account,setAccount]=useState('all');const [skipping,setSkipping]=useState(null);const [signed,setSigned]=useState({});
 const load=async()=>{setLoading(true);setError('');api.signedPdfList().then(d=>setSigned(Object.fromEntries((d.items||[]).map(x=>[x.request_id,x.signed_pdfs])))).catch(()=>setSigned({}));try{const [s,r]=await Promise.all([api.stats(),api.requests()]);setStats(s);setRows(r.items||[])}catch(e){setError(e.message||'Failed to load requests')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const modifiedAccounts=useMemo(()=>new Set(rows.filter(r=>(r.change_types||[]).length).map(r=>r.client_code||`id:${r.id}`)),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const isMod=modifiedAccounts.has(r.client_code||`id:${r.id}`);if(account==='modified'&&!isMod)return false;if(account==='unmodified'&&isMod)return false;const text=`${r.client_code} ${r.operation_id} ${r.change_label}`.toLowerCase();return (!search||text.includes(search.toLowerCase()))&&(status==='all'||(status==='esign_completed'?!!signed[r.id]?.length:(r.status||'').toLowerCase().includes(status)))&&(type==='all'||r.change_type===type||(r.change_types||[]).includes(type))}),[rows,search,status,type,account,modifiedAccounts,signed]);
 const skipPayment=async r=>{if(!confirm(`Skip payment for ${r.client_code} and move to the next step?`))return;setSkipping(r.id);try{const {payment}=await api.skipPayment(r.id);setRows(rs=>rs.map(x=>x.id===r.id?{...x,payment}:x))}catch(e){alert(e.message||'Could not skip payment')}finally{setSkipping(null)}};
 const logout=()=>{localStorage.removeItem('rekyc_admin_token');location.href='/login'};
 return <div className="app-shell"><header className="topbar"><div className="brand"><img src="/aionion-logo.png"/><div><b>AEON ReKYC Admin</b><span>KYC Operations & Verification</span></div></div><div className="top-actions"><button className="bell"><Bell size={19}/><i/></button><div className="admin-chip"><div>A</div><span><b>Admin</b><small>KYC Team</small></span><ChevronDown size={16}/></div><button className="logout" onClick={logout}><LogOut size={17}/> Logout</button></div></header>
 <main className="dashboard"><div className="page-title"><div><p>OPERATIONS / REKYC</p><h1>Modification Requests</h1><span>Review one active client change at a time and submit verified requests for downstream processing.</span></div><button className="refresh" onClick={load}><RefreshCw size={17} className={loading?'spin':''}/> Refresh</button></div>
 <div className="stats-grid three"><StatCard label="Total Account Count" value={stats.totalAccounts} icon={Files} sub="All ReKYC accounts" tone="blue"/><StatCard label="Modified Account Count" value={stats.modifiedAccounts} icon={CheckCircle2} sub="Accounts with a change request" tone="green"/><StatCard label="Unmodified Account Count" value={stats.unmodifiedAccounts} icon={Clock3} sub="Accounts with no changes" tone="amber"/></div>
 <div className="content-card"><div className="card-toolbar"><div><h2>Client ReKYC Queue</h2><p>Latest client change requests with verification readiness.</p></div><div className="lock-rule"><ShieldCheck size={18}/><span><b>One-change lock active</b><small>Next change allowed only after admin decision</small></span></div></div>
 <div className="filters"><div className="search"><Search size={18}/><input placeholder="Search client code / operation ID..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="select-wrap"><Filter size={16}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option><option value="esign_completed">eSign Completed</option></select></div><div className="select-wrap"><select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(t=><option key={t} value={t}>{t==='all'?'All Change Types':t[0].toUpperCase()+t.slice(1)}</option>)}</select></div><div className="select-wrap"><select value={account} onChange={e=>setAccount(e.target.value)}><option value="all">All Accounts</option><option value="modified">Modified Account</option><option value="unmodified">Unmodified Account</option></select></div></div>
 <div className="table-wrap"><table><thead><tr><th>Client</th><th>Change Type</th><th>Date</th>{CHANGE_COLS.map(c=><React.Fragment key={c.type}><th>Old_{c.label}</th><th>New_{c.label}</th></React.Fragment>)}<th>DDPI</th><th>Payment</th><th>Signed PDF</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.client_code}</b></td><td>{r.change_types?.length?<div className="type-list">{r.change_types.map(t=><span key={t} className={`type-pill ${t}`}>{TYPE_LABELS[t]}</span>)}</div>:<span className={`type-pill ${r.change_type}`}>{r.change_label}</span>}</td><td style={{whiteSpace:'nowrap'}}>{r.otp_date||'—'}</td>{CHANGE_COLS.map(c=><React.Fragment key={c.type}><Cell r={r} type={c.type} field="old"/><Cell r={r} type={c.type} field="next"/></React.Fragment>)}<Cell r={r} type="ddpi" field="next"/><PaymentCell p={r.payment} busy={skipping===r.id} onSkip={()=>skipPayment(r)}/><td className="value-cell">{signed[r.id]?.length?<SignedPdfButtons id={r.id} pdfs={signed[r.id]} compact/>:<span className="pdf-pending">eSign pending</span>}</td><td><button className="view-btn" onClick={()=>setSelected(r.id)}><Eye size={17}/> Review</button></td></tr>)}</tbody></table>{error?<div className="empty" style={{color:'#d64545'}}>Could not load requests: {error}</div>:!filtered.length&&<div className="empty">No requests match the selected filters.</div>}</div>
 </div></main><RequestDrawer id={selected} onClose={()=>setSelected(null)} onChanged={load}/></div>
}
